### ISSUE TITLE
ULg logo remains visible in presenter mode

### ISSUE THREAD

**Issue by glouppe** [glouppe/info8002-large-scale-data-systems#2]
Hey @JoeriHermans 

I just found a small bug with the logo. When in presenter mode (press `p`), the ULg logo remains visible.

Nothing urgent, but would be nice to fix.

**Comment by JoeriHermans** [comment]
Oh I see. It seems that Remark does some internal DOM reshuffling (at least I think so), logo stays present due to :first-child selector. Will look for a fix!

**Comment by glouppe** [comment]
Fixed in 4be6e821ee103dc9044b1d4a17922ddd5256962c

Instead, I created a `title-slide` css class, which I assign to the first slides through the `class:` attribute in remark.
