### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by JoeriHermans** [glouppe/info8002-large-scale-data-systems#5]
Should we maintain a list of possible projects in a Markdown file?

**Comment by glouppe** [comment]
Or rather brainstorm a list of project ideas in this issue?

**Comment by JoeriHermans** [comment]
I have an idea for a small "starter" project, since designing such systems also requires the knowledge to implement a protocol (to some extend).

As a first (very simple) project, I would propose to let the students implement a specific RFC designed by us. I was thinking about something like this:
- We have a list of all students which subscribed to the list.
- A webpage visualized (red/green) if they implemented the protocol message correctly.
- We host a machine which accepts a UDP packet in the following format, and updates webpage accordingly.

- 4 bytes unsigned (network byte order) for representing their student id.
- 4 bytes unsigned (network byte order) UNIX timestamp.
- 1 byte unsigned (message options):
    - First 4 bits (0x0)
    - Fifth bit (flag indicating if you want to pass the assignment, set accordingly :))
    - Sixth bit (flag indicating whether your student-id is odd or even)
    - Seventh & eight bit (0x4)

Optional: not required
- 2 unsigned bytes payload length (network byte-order)
- (payload length bytes) identifier id you received from us

Let me know what you think, may be unnecessary.

Joeri

**Comment by glouppe** [comment]
Hi Joeri,

For the small projects, it might be nice to have a continued project where they have to implement several pieces of a distributed system. E.g., failure detection, consensus or other things that will be covered in the first half of the course. I am not sure to see what would be the goal of your first assignment? 

In https://www.cse.buffalo.edu/~stevko/courses/cse486/spring16/schedule.html for example, the first project is to implement a group messaging system. Effectively, they have to implement multicast with some consistency guarantees. I think this is feasible. 

Something important to think about carefully is to determine how to build an actual distributed system (framework, api, machines, etc) or if we decide to simulate it and how.  

For the second half, I think it will be easier to design projects :)

**Comment by JoeriHermans** [comment]
Hi Gilles,

Yes, you are right, this isn't really "reusable". The project you suggested however should be very feasible :) Depending on what you are planning to do (e.g., 1 project like this and 1 with Spark, ...), we could let them implement a DHT which should also be very doable imho. Furthermore, to do this, they also need to implement failure recovery and maintain certain invariants (depending on the implementation they choose). So maybe this might also be a good exercise. However, this might be too much, especially if we want to let them do something with Spark since it takes some time to get used to the programming model.

Kind regards,

Joeri
