### ISSUE TITLE
Reference book

### ISSUE THREAD

**Issue by skulasik** [glouppe/info8002-large-scale-data-systems#7]
The reference book is "Introduction to Reliable Distributed Programming" or the other one shown on the picture in slides "Introduction to Reliable and Secure Distributed Programming"?

**Comment by glouppe** [comment]
Those are actually the same book. "Introduction to Reliable and Secure Distributed Programming" is the second version of "Introduction to Reliable Distributed Programming".

Read the latest version. 

I'll update the reference in the notes.

**Comment by glouppe** [comment]
Fixed in 3044209c53b41b1e3f9a89067e154a363916a45b
